//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int campaign_id { get; set; }
        public int discountRate { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime lastDate { get; set; }
        public string compaignDetail { get; set; }
        public int product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
