//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Detail
    {
        public int productDetail_id { get; set; }
        public string properties { get; set; }
        public string propertiesDetail { get; set; }
        public int product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
